[2024-04-29 23:48:00,309: INFO: main: Welcome to our custom log]
[2024-05-01 12:16:25,000: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 12:16:25,016: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 12:16:25,019: INFO: common: created directory at: artifacts]
[2024-05-01 12:16:25,021: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-01 12:16:25,022: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 12:17:11,019: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 12:41:46,060: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-01 12:41:46,062: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 12:41:46,063: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 12:41:46,063: INFO: common: created directory at: artifacts]
[2024-05-01 12:41:46,064: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-01 12:41:46,064: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 12:42:28,945: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 12:42:30,052: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-01 18:41:47,848: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 18:41:47,864: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 18:41:47,867: INFO: common: created directory at: artifacts]
[2024-05-01 18:41:47,868: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-01 18:41:57,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 18:41:57,652: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 18:41:57,656: INFO: common: created directory at: artifacts]
[2024-05-01 18:41:57,657: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-01 18:42:44,400: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-01 18:59:26,768: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-01 18:59:26,771: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 18:59:26,773: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 18:59:26,773: INFO: common: created directory at: artifacts]
[2024-05-01 18:59:26,775: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-01 18:59:26,775: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 19:00:57,090: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 19:00:58,370: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-01 19:00:58,371: INFO: main: *******************]
[2024-05-01 19:00:58,371: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-01 19:00:58,375: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 19:00:58,379: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 19:00:58,381: INFO: common: created directory at: artifacts]
[2024-05-01 19:00:58,382: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-01 19:00:59,239: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-01 19:00:59,502: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-01 20:23:56,506: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 20:23:56,520: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 20:23:56,525: INFO: common: created directory at: artifacts]
[2024-05-01 20:23:56,528: INFO: common: created directory at: artifacts\training]
[2024-05-01 20:43:14,755: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-01 20:43:14,758: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 20:43:14,762: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 20:43:14,763: INFO: common: created directory at: artifacts]
[2024-05-01 20:43:14,764: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-01 20:43:14,764: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 20:44:08,523: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 20:44:09,463: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-01 20:44:09,465: INFO: main: *******************]
[2024-05-01 20:44:09,465: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-01 20:44:09,467: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 20:44:09,469: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 20:44:09,470: INFO: common: created directory at: artifacts]
[2024-05-01 20:44:09,471: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-01 20:44:10,269: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-01 20:44:10,588: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-01 20:44:10,588: INFO: main: *******************]
[2024-05-01 20:44:10,588: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-01 20:44:10,591: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 20:44:10,594: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 20:44:10,595: INFO: common: created directory at: artifacts]
[2024-05-01 20:44:10,596: INFO: common: created directory at: artifacts\training]
[2024-05-01 20:45:11,403: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-01 21:53:12,850: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 21:53:12,857: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 21:53:12,860: INFO: common: created directory at: artifacts]
[2024-05-01 21:53:34,333: INFO: common: json file saved at: scores.json]
[2024-05-01 21:53:46,808: WARNING: connectionpool: Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001899A060610>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow/runs/create]
[2024-05-01 21:54:02,862: WARNING: connectionpool: Retrying (Retry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000018999FF6A60>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow/runs/create]
[2024-05-01 21:54:22,926: WARNING: connectionpool: Retrying (Retry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001899A04D5B0>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow/runs/create]
[2024-05-01 21:54:50,979: WARNING: connectionpool: Retrying (Retry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001899A04D700>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow/runs/create]
[2024-05-01 21:55:00,559: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-01 21:55:01,187: INFO: builder_impl: Assets written to: C:\Users\Dell\AppData\Local\Temp\tmpeo1__8a9\model\data\model\assets]
[2024-05-01 21:55:47,842: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow/runs/get?run_uuid=c152a929a57e46f184039f8fa613f82a&run_id=c152a929a57e46f184039f8fa613f82a]
[2024-05-01 21:56:12,096: WARNING: connectionpool: Retrying (Retry(total=3, connect=5, read=3, redirect=5, status=5)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow/runs/get?run_uuid=c152a929a57e46f184039f8fa613f82a&run_id=c152a929a57e46f184039f8fa613f82a]
[2024-05-01 21:56:44,040: WARNING: connectionpool: Retrying (Retry(total=2, connect=5, read=2, redirect=5, status=5)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow/runs/get?run_uuid=c152a929a57e46f184039f8fa613f82a&run_id=c152a929a57e46f184039f8fa613f82a]
[2024-05-01 21:57:31,906: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow-artifacts/artifacts/bb176e1a681f484a9fce52dd41e33ae6/c152a929a57e46f184039f8fa613f82a/artifacts/model/python_env.yaml]
[2024-05-01 21:57:52,229: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow-artifacts/artifacts/bb176e1a681f484a9fce52dd41e33ae6/c152a929a57e46f184039f8fa613f82a/artifacts/model/data/model/keras_metadata.pb]
[2024-05-01 21:58:08,358: WARNING: connectionpool: Retrying (Retry(total=3, connect=4, read=4, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001899AC531F0>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow-artifacts/artifacts/bb176e1a681f484a9fce52dd41e33ae6/c152a929a57e46f184039f8fa613f82a/artifacts/model/data/model/keras_metadata.pb]
[2024-05-01 21:58:25,330: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow-artifacts/artifacts/bb176e1a681f484a9fce52dd41e33ae6/c152a929a57e46f184039f8fa613f82a/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-05-01 21:59:03,796: WARNING: connectionpool: Retrying (Retry(total=3, connect=5, read=3, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow-artifacts/artifacts/bb176e1a681f484a9fce52dd41e33ae6/c152a929a57e46f184039f8fa613f82a/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-05-01 22:04:45,902: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 22:04:45,905: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 22:04:45,907: INFO: common: created directory at: artifacts]
[2024-05-01 22:05:05,697: INFO: common: json file saved at: scores.json]
[2024-05-01 22:05:10,219: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-01 22:05:10,806: INFO: builder_impl: Assets written to: C:\Users\Dell\AppData\Local\Temp\tmpjuejlyxj\model\data\model\assets]
[2024-05-01 22:06:05,076: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow-artifacts/artifacts/bb176e1a681f484a9fce52dd41e33ae6/9d5f204657f14593bb54fafe9f0bc225/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-05-01 22:07:33,118: WARNING: connectionpool: Retrying (Retry(total=3, connect=5, read=3, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /ramasaranmummidi/Kidney-Disease-Detection-using-Deep-Learning.mlflow/api/2.0/mlflow-artifacts/artifacts/bb176e1a681f484a9fce52dd41e33ae6/9d5f204657f14593bb54fafe9f0bc225/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-05-01 22:17:29,100: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 22:17:29,104: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 22:17:29,107: INFO: common: created directory at: artifacts]
[2024-05-01 22:19:32,664: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 22:19:32,674: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 22:19:32,676: INFO: common: created directory at: artifacts]
[2024-05-01 22:19:54,302: INFO: common: json file saved at: scores.json]
[2024-05-01 22:19:58,129: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-01 22:19:58,783: INFO: builder_impl: Assets written to: C:\Users\Dell\AppData\Local\Temp\tmpybvfputd\model\data\model\assets]
[2024-05-01 23:24:26,198: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-01 23:24:26,207: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:24:26,215: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:24:26,216: INFO: common: created directory at: artifacts]
[2024-05-01 23:24:26,216: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-01 23:24:26,217: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 23:25:14,291: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 23:25:15,310: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-01 23:25:15,312: INFO: main: *******************]
[2024-05-01 23:25:15,313: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-01 23:25:15,319: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:25:15,324: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:25:15,325: INFO: common: created directory at: artifacts]
[2024-05-01 23:25:15,326: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-01 23:25:16,010: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-01 23:25:16,376: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-01 23:25:16,376: INFO: main: *******************]
[2024-05-01 23:25:16,376: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-01 23:25:16,381: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:25:16,383: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:25:16,383: INFO: common: created directory at: artifacts]
[2024-05-01 23:25:16,384: INFO: common: created directory at: artifacts\training]
[2024-05-01 23:27:22,575: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-01 23:27:22,578: INFO: main: *******************]
[2024-05-01 23:27:22,578: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-01 23:27:22,585: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:27:22,589: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:27:22,590: INFO: common: created directory at: artifacts]
[2024-05-01 23:27:42,141: INFO: common: json file saved at: scores.json]
[2024-05-01 23:27:42,143: INFO: common: json file saved at: scores.json]
[2024-05-01 23:27:42,144: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-01 23:29:23,125: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-01 23:29:23,128: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:29:23,130: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:29:23,130: INFO: common: created directory at: artifacts]
[2024-05-01 23:29:23,131: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-01 23:29:23,131: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 23:30:08,385: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 23:30:09,211: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-01 23:30:09,211: INFO: main: *******************]
[2024-05-01 23:30:09,212: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-01 23:30:09,215: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:30:09,217: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:30:09,218: INFO: common: created directory at: artifacts]
[2024-05-01 23:30:09,218: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-01 23:30:09,939: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-01 23:30:10,342: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-01 23:30:10,343: INFO: main: *******************]
[2024-05-01 23:30:10,343: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-01 23:30:10,351: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:30:10,353: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:30:10,354: INFO: common: created directory at: artifacts]
[2024-05-01 23:30:10,355: INFO: common: created directory at: artifacts\training]
[2024-05-01 23:32:14,266: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-01 23:32:14,267: INFO: main: *******************]
[2024-05-01 23:32:14,267: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-01 23:32:14,273: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:32:14,276: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:32:14,278: INFO: common: created directory at: artifacts]
[2024-05-01 23:32:34,534: INFO: common: json file saved at: scores.json]
[2024-05-01 23:32:34,535: INFO: common: json file saved at: scores.json]
[2024-05-01 23:32:38,330: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-01 23:32:39,001: INFO: builder_impl: Assets written to: C:\Users\Dell\AppData\Local\Temp\tmpn2vjjokm\model\data\model\assets]
[2024-05-01 23:33:59,194: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "c:\users\dell\desktop\p1\kidney-disease-detection-using-deep-learning\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\dell\desktop\p1\kidney-disease-detection-using-deep-learning\src\cnnClassifier\components\model_evaluation_mlflow.py", line 72, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 562, in log
    mlflow.register_model(
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 77, in register_model
    raise e
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 68, in register_model
    create_model_response = client.create_registered_model(name)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1743, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\store\model_registry\rest_store.py", line 75, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 42, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: ''
[2024-05-01 23:37:09,056: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-01 23:37:09,058: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:37:09,060: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:37:09,060: INFO: common: created directory at: artifacts]
[2024-05-01 23:37:09,061: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-01 23:37:09,061: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 23:38:10,086: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-01 23:38:10,940: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-01 23:38:10,940: INFO: main: *******************]
[2024-05-01 23:38:10,941: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-01 23:38:10,945: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:38:10,947: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:38:10,948: INFO: common: created directory at: artifacts]
[2024-05-01 23:38:10,948: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-01 23:38:11,735: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-01 23:38:12,042: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-01 23:38:12,042: INFO: main: *******************]
[2024-05-01 23:38:12,042: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-01 23:38:12,044: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:38:12,046: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:38:12,048: INFO: common: created directory at: artifacts]
[2024-05-01 23:38:12,049: INFO: common: created directory at: artifacts\training]
[2024-05-01 23:40:14,759: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-01 23:40:14,759: INFO: main: *******************]
[2024-05-01 23:40:14,760: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-01 23:40:14,769: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 23:40:14,776: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 23:40:14,777: INFO: common: created directory at: artifacts]
[2024-05-01 23:40:34,619: INFO: common: json file saved at: scores.json]
[2024-05-01 23:40:34,623: INFO: common: json file saved at: scores.json]
[2024-05-01 23:40:38,111: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-01 23:40:38,762: INFO: builder_impl: Assets written to: C:\Users\Dell\AppData\Local\Temp\tmpaz175p7p\model\data\model\assets]
[2024-05-01 23:41:49,872: ERROR: main: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    model_evalution.main()
  File "c:\users\dell\desktop\p1\kidney-disease-detection-using-deep-learning\src\cnnClassifier\pipeline\stage_04_model_evaluation.py", line 20, in main
    evaluation.log_into_mlflow()
  File "c:\users\dell\desktop\p1\kidney-disease-detection-using-deep-learning\src\cnnClassifier\components\model_evaluation_mlflow.py", line 72, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model", registered_model_name="VGG16Model")
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\tensorflow\__init__.py", line 222, in log_model
    return Model.log(
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\models\model.py", line 562, in log
    mlflow.register_model(
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 77, in register_model
    raise e
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\fluent.py", line 68, in register_model
    create_model_response = client.create_registered_model(name)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\client.py", line 1743, in create_registered_model
    return self._get_registry_client().create_registered_model(name, tags, description)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\tracking\_model_registry\client.py", line 63, in create_registered_model
    return self.store.create_registered_model(name, tags, description)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\store\model_registry\rest_store.py", line 75, in create_registered_model
    response_proto = self._call_endpoint(CreateRegisteredModel, req_body)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\store\model_registry\base_rest_store.py", line 42, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 281, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "C:\Users\Dell\anaconda3\envs\kidney\lib\site-packages\mlflow\utils\rest_utils.py", line 213, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/registered-models/create failed with error code 403 != 200. Response body: ''
